nelmio_api_doc:
  areas:
    path_patterns:
      - ^/api(?!/doc(.json)?$)
  documentation:
    info:
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          description: 'Authorization: Bearer {value}'
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []