security:
    encoders:
        Symfony\Component\Security\Core\User\User: auto

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$argon2id$v=19$m=65536,t=4,p=1$UYz0OqBqDOnvRH635kgHxA$KRy3ATlCygbz7Y/CDs3Xn4MXn6ilX8TkYruCIU4ZlY8'
                        roles: ['ROLE_API']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/api/doc, roles: ROLE_API }