security:
    encoders:
        Symfony\Component\Security\Core\User\User: auto

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$argon2id$v=19$m=65536,t=4,p=1$UYz0OqBqDOnvRH635kgHxA$KRy3ATlCygbz7Y/CDs3Xn4MXn6ilX8TkYruCIU4ZlY8'
                        roles: ['ROLE_API']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            stateless: true
            provider: in_memory
            json_login:
                check_path: /authentication_token
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_API }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }