security:
    encoders:
        Symfony\Component\Security\Core\User\User: auto

    providers:
        in_memory:
            memory:
                users:
                    '%env(API_USERNAME)%':
                        password: '%env(API_PASSWORD)%'
                        roles: ['ROLE_API']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api-doc:
            anonymous: ~
            http_basic: ~
            pattern: ^/api/doc(.json)?
        main:
            anonymous: ~
            stateless: true
            provider: in_memory
            json_login:
                check_path: /authentication_token
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api, roles: ROLE_API }
        - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }